### PR TITLE
gcal add-on workspaces

### PR DESCRIPTION
**Pull request by bmichalek**
GCal add-on rework to support workspaces. 

Currently a new MeetLater room is created without belonging to a specific workspace. However to finish calendar integration we need to have all MeetLater rooms properly assigned to a workspace.

gcal1

---

There is however one thing that might be a little bit confusing for the user ... when user changes workspace and then closes the event card, add-on still shows previously selected workspace and not the new one. This is due to how the cards are pushed onto the stack ... so basically card that is on top of the stack changes something and card below it is not updated. I've spent several days trying to figure that out but no luck so far 😞 

gcal2

---

I've also refactored the code a bit to make it more readable as it was quite a mess 😬 

---

@vladoh @kstefanikova just fyi if you'd like to tweak some copy a bit. There is not much we can do regarding design, we have to use predefined components that can't be customized too much.

### CODE REVIEW

**Comment by kstefanikova** [comment]
Thanks, @bmichalek! In addition the questions I asked in Slack, could you pls tweak all those new CTAs? We already use this black button on the login screen.

Screenshot 2023-08-24 at 11 03 04

**Comment by bmichalek** [comment]
> Thanks, @bmichalek! In addition the questions I asked in Slack, could you pls tweak all those new CTAs? We already use this black button on the login screen.
> 
> Screenshot 2023-08-24 at 11 03 04

What? There are no new CTAs

**Comment by kstefanikova** [comment]
> > Thanks, @bmichalek! In addition the questions I asked in Slack, could you pls tweak all those new CTAs? We already use this black button on the login screen.
> > Screenshot 2023-08-24 at 11 03 04
> 
> What? There are no new CTAs

So existing ones :) Can we do something with these CTAs or not?
Screenshot 2023-08-24 at 11 21 56

**Comment by bmichalek** [comment]
> > > Thanks, @bmichalek! In addition the questions I asked in Slack, could you pls tweak all those new CTAs? We already use this black button on the login screen.
> > > Screenshot 2023-08-24 at 11 03 04
> > 
> > 
> > What? There are no new CTAs
> 
> So existing ones :) Can we do something with these CTAs or not? At least adjusting font-weight. Match it with the login button
> 
> Screenshot 2023-08-24 at 11 21 56

No, we can't customize it.

**Review by rubengglez-miro — APPROVED** [review]
LGTM

**Comment by vladoh** [comment]
Feedback from Patrick on desired copy:
Screenshot 2023-08-30 at 3 36 05 PM

**Comment by bmichalek** [comment]
Updated copy based on ^^

**Pull request merged**
